name: dbc_snippets
description: A sample command-line application.
version: 1.0.0
publish_to: none

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  design_by_contract:
    path: /Users/ankozyrenko/Desktop/Other programming stuff/thesis/dbc-library

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
